/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.oogis.myTable.v1.ui;

import org.jdesktop.swingx.JXTreeTable;
import org.jdesktop.swingx.treetable.AbstractMutableTreeTableNode;
import org.jdesktop.swingx.treetable.DefaultTreeTableModel;
import ru.oogis.myTable.v1.data.Data;
import ru.oogis.myTable.v1.data.Human;
import ru.oogis.myTable.v1.data.HumanGroup;

import java.util.Arrays;
import java.util.List;

/**
 * @author smekto4ka
 */
public class PanelWithTable extends javax.swing.JPanel {
    private Data data;

    private String[] nameColumn = {"Имя", "возраст", "город", "енергия"};

    /**
     * Creates new form Panel
     */
    public PanelWithTable(Data data) {
        this.data = data;
        initComponents();
        DefaultTreeTableModel model = new DefaultTreeTableModel(getNode(), Arrays.asList(nameColumn));
        JXTreeTable table = new JXTreeTable(model);
        jScrollPane1.add(table);

        add(table);
        table.setShowGrid(true, true);
        table.setColumnControlVisible(true);

        table.packAll();
    }

    private AbstractMutableTreeTableNode getNode() {
        StringNode stringNode = new StringNode("table");

        for (HumanGroup group : data.getHumanGroups()) {
            GroupNode groupNode = new GroupNode(group);
            for (Human human : group.getHumans()) {
                HumanNode humanNode = new HumanNode(human);
                groupNode.add(humanNode);
            }
            stringNode.add(groupNode);
        }
        return stringNode;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());
        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
