/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.oogis.redevelopment.ui;

import ru.oogis.redevelopment.Start;
import ru.oogis.redevelopment.data.model.Building;
import ru.oogis.redevelopment.data.model.WrapperForTheGlobalTable;

import java.util.List;
import java.util.Map;

/**
 * @author �
 */
public class FrameForGlobalTable extends javax.swing.JFrame {


    /**
     * Creates new form FrameForGlobalTable
     */

    public FrameForGlobalTable(WrapperForTheGlobalTable wrapperForTheGlobalTable) {
        initComponents();
        add(new PanelWithGlobalTable(wrapperForTheGlobalTable));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
